#!/bin/sh
set -e -x
git --version
upstream=$1
: ${upstream:=origin}
: ${REPO:=git@github.com:watchout-tw/blog.citizenedu.tw.git}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi
npm i
rm -rf build
# XXX: use --reference when not in shallow clone
#git clone $REPO --reference . -b gh-pages build
git clone $REPO -b gh-pages build
mv build/.git tmp-git

REV=`git describe --always`
BUILD=git-$REV npm run build
mv tmp-git build/.git
cp CNAME build
cd build
git add -Af .
echo "regen for $REV" | git commit-tree `git write-tree` -p `git rev-parse HEAD` -p $REV | xargs git reset --hard
git push origin gh-pages
cd ..
